version: "3.7"
services:
  redis:
    image: "redis:alpine"
    container_name: fizzbang_redis

    command: redis-server --requirepass super_secret

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

